name: Build cpython-asan image
run-name: Build cpython-asan -- ${{ inputs.python_version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: Version of Python to build (e.g. '3.14.3t' or '3.14t' or '3.15t-dev')
        default: '3.15t-dev'
        type: string
  schedule:
    # 04:02 on Sundays and Wednesdays
    - cron: "02 4 * * SUN,WED"

env:
  python_version: ${{ github.event.inputs.python_version || '3.15t-dev' }}

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Login to ghcr
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
       registry: ghcr.io
       username: ${{ github.repository_owner }}
       password: ${{ secrets.CI_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Compute tags
      run: |
        bash .github/scripts/compute_tags.sh ghcr.io/nascheme/cpython-asan "${{ env.python_version }}" >> $GITHUB_ENV

    - name: Build and push image -- ${{ env.python_version }}
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
      with:
       context: .
       push: true
       file: ./Dockerfile.cpython
       build-args: |
        python_version=${{ env.python_version }}
        config_opts=--with-address-sanitizer
       tags: ${{ env.TAGS }}
