name: Build numpy-tsan image

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: Version of Python to build
        default: '3.15t-dev'
        type: choice
        options:
        - '3.13t'
        - '3.14t'
        - '3.15t-dev'
  schedule:
    # 03:22 on Sundays and Wednesdays
    - cron: "22 3 * * SUN,WED"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
       registry: ghcr.io
       username: ${{ github.repository_owner }}
       password: ${{ secrets.CI_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
       context: .
       push: true
       build-args: |
        base_image=ghcr.io/nascheme/cpython-tsan:${{ inputs.python_version || '3.15t-dev' }}
       file: ./Dockerfile.numpy
       tags: |
        ghcr.io/nascheme/numpy-tsan:${{ inputs.python_version || '3.15t-dev' }}
