name: Build and push numpy image to ghcr

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
       registry: ghcr.io
       username: ${{ github.repository_owner }}
       password: ${{ secrets.CI_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
       context: .
       push: true
       build-args: |
        base_image=ghcr.io/nascheme/cpython-tsan:latest
       cache-from: type=gha
       cache-to: type=gha,mode=max
       file: ./Dockerfile.numpy
       tags: |
        ghcr.io/nascheme/numpy-tsan:latest
